name: AfkPool
version: '${project.version}'
main: org.minecraft.plugin.afkpool.AfkPool
api-version: '1.20'

description: A plugin to reward AFK players.
author: Cveleee
depend: [WorldGuard, WorldEdit]

commands:
  ap:
    usage: /<command>
    aliases: []