name: AfkPool
version: '${project.version}'
main: org.minecraft.plugin.afkpool.AfkPool
api-version: '1.20'

description: A plugin to reward AFK players.
author: Cveleee
depend: [WorldGuard, WorldEdit]

commands:
  afkpool:
    description: Main command for AfkPool plugin
    aliases: [ap]
    usage: /<command> help
  ap:
    description: Alias for AfkPool main command
    aliases: [afkpool]
    usage: /<command> help